version: '3.7'
services:
  debian:
    build:
      context: .
      dockerfile: Debian_dockerfile
    environment: 
      - container=docker
      - TZ=UTC
    #network_mode: "host"
    restart: on-failure
    tmpfs: 
       - /tmp:exec
       - /run
       - /run/lock
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    working_dir: /app
    privileged: true
    tty: true
    ports:
       - "5601:5601"
       - "9200:9200"
       - "9300:9300"
