version: '3.7'
services:
  centos7:
    image: 'perfsonar/logstash/qa:centos7'
    build:
      context: .
      dockerfile: docker/centos7/Dockerfile
    tmpfs: 
       - /run
       - /tmp
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    working_dir: /app