version: '3.7'
services:
  ansible_runner:
    image: 'ansible/ansible-runner:1.4.6'
    volumes:
      - .:/app
    working_dir: /app/ansible
    environment:
      - RUNNER_PLAYBOOK=/app/ansible/playbook.yml